### ISSUE TITLE
Error when building netcdf with netcdf4 for input into genericdataset 

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [neuralhydrology/neuralhydrology#56] opened 2021-12-27 23:56 UTC
Hello I actually found a work around but wanted to put this out there 1) as a curiosity and 2) incase anyone else came across the same issue. I was trying to run NH with some generic data using the genericdataset function but kept getting something similar to:
 
TypeError: cannot do slice indexing on RangeIndex with these indexers [1999-09-30 23:59:59.999999636] of type Timestamp

So then I created an identical (it seemed identical to me) nc file using xarray: 
```

for f in files:
    # Read in raw netcdf file
    nc_file_in = Dataset(f'{input_folder}/{f}')
    # Extract time_steps, e.g. days
    time_steps = nc_file_in.variables["time"].shape[0]
    # Extract basin
    basin = f.split(".")[0]
    
    # Create a new array and date coordinate that averages over the basin
    ds = xr.Dataset(
       {"tmax": (("date"), np.ma.average(nc_file_in.variables["tmax"][:,:,:],lat_lon_index) ),
        "prcp": (("date"), np.ma.average(nc_file_in.variables["prcp"][:,:,:],lat_lon_index) ),
        # Pull in streamflow 
        "QObs": (("date"), stream_flow[basin] )},
        # Create date-time index
         coords={
             "date": pd.date_range(start_date, periods=time_steps, freq='D'),
       },
    )
    # Close out input file
    nc_file_in.close()
    # Print new averaged nc file
    ds.to_netcdf(f'{output_folder}/{basin}.nc')

```
and it worked fine...

**Comment by kratzert** [comment] 2022-01-05 14:24
Hi @Flash-Of-Thunder 

not really sure what is happening here and from what you provide it is really hard to test. My guess is that the problem is the time index (which probably should be 00:00:0000000 instead of 23:59:59.999999636) and that this is causing the problems. When you recreate the netCDF, you create a date-range with `freq='D'`, which will result in cleaner date time indices, which might be the reason why it works.

As I don't really see a problem here with our code, I will close this issue. Feel free to reopen, if you think this is a problem on our side but then please provide more data/info so that we could reproduce this error.

**Closed by kratzert** 2022-01-05 14:24 UTC

**Comment by Flash-Of-Thunder** [comment] 2022-01-05 19:33
> not really sure what is happening here and from what you provide it is really hard to test. My guess is that the problem is the time index (which probably should be 00:00:0000000 instead of 23:59:59.999999636) and that this is causing the problems. **When you recreate the netCDF, you create a date-range with `freq='D'`, which will result in cleaner date time indices, which might be the reason why it works.**

I think you are correct here, this was my thought after working with the models and data more. I was going to try and rerun my old code that used netcdf4 with `freq='D'` to test this but accidently saved over my old netcdf4 code. 

As for the lack of information in the post, I was trying to avoid making a massive post, but I see now that having too little detail is even worse. 

Thanks!
