### ISSUE TITLE
Error running 06_Finetuning notebook

### ISSUE THREAD

**Issue by everettsp** [neuralhydrology/neuralhydrology#105] opened 2023-01-27 04:07 UTC
I'm getting an error while running the Finetuning example. The initial 531 basin model trains fine, but the Finetuning function throws an error when trying to calculate the scaler on a single basin. I think this is due to a `self._get_dataset` call before the `self.cfg._is_finetuning` check in `basetrainer.py`. Encountering error on a freshly installed environment on Windows.

Error and finetune.yml config (default file) copied below, let me know if you need any other information.

Thanks,
Everett

**Error**
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18296\3717755737.py in <module>
----> 1 finetune(Path("finetune.yml"))

~\Documents\GitHub\neuralhydrology\neuralhydrology\nh_run.py in finetune(config_file, gpu)
    141         config.device = "cpu"
    142 
--> 143     start_training(config)
    144 
    145 

~\Documents\GitHub\neuralhydrology\neuralhydrology\training\train.py in start_training(cfg)
     20     else:
     21         raise ValueError(f"Unknown head {cfg.head}.")
---> 22     trainer.initialize_training()
     23     trainer.train_and_validate()

~\Documents\GitHub\neuralhydrology\neuralhydrology\training\basetrainer.py in initialize_training(self)
    139         If called in a ``continue_training`` context, this model will also restore the model and optimizer state.
    140         """
--> 141         ds = self._get_dataset()
    142         if len(ds) == 0:
    143             raise ValueError("Dataset contains no samples.")
...
    110 
    111     # Check for NaNs in any attribute of any basin

RuntimeError: The following attributes have a std of zero or NaN, which results in NaN's when normalizing the features. Remove the attributes from the attribute feature list and restart the run. 
Attributes: ['elev_mean', 'slope_mean', 'area_gages2', 'frac_forest', 'lai_max', 'lai_diff', 'gvf_max', 'gvf_diff', 'soil_depth_pelletier', 'soil_depth_statsgo', 'soil_porosity', 'soil_conductivity', 'max_water_content', 'sand_frac', 'silt_frac', 'clay_frac', 'carbonate_rocks_frac', 'geol_permeability', 'p_mean', 'pet_mean', 'aridity', 'frac_snow', 'high_prec_freq', 'high_prec_dur', 'low_prec_freq', 'low_prec_dur']

```
**Run file**
```
experiment_name: cudalstm_531_basins_finetuned

train_basin_file: finetune_basin.txt
validation_basin_file: finetune_basin.txt
test_basin_file: finetune_basin.txt

learning_rate:
    0: 5e-4
    2: 5e-5	

epochs: 10

finetune_modules:
- head
- lstm

base_run_dir: c:\Users\everett\Documents\GitHub\neuralhydrology\examples\06-Finetuning\runs\cudalstm_531_basins_2501_182111
```

**Comment by Corinna-Frank** [comment] 2023-01-27 15:09
Hi @everettsp,

I am encountering the exact same issue. I adapted the package on my local machine as a workaround as follows:
in `basetrainer.py` in `def initialize_training` added a call to get the scaler before getting the dataset:
```
def initialize_training(self):

        if self.cfg.is_finetuning:
            self._scaler = load_scaler(self.cfg.base_run_dir)
            
        ds = self._get_dataset()
       ...
```
in addition, in `basedataset.py` line 93 added an additional condition:
```
        if is_train and not scaler and not self.cfg.is_finetuning:
            self._compute_scaler = True
```
Not sure if this is the correct way to modify the code, but at least I can run it now without an error. Hope this helps!

Cheers,
Corinna

**Comment by kratzert** [comment] 2023-01-27 18:43
Hi @everettsp,

absolutely no idea what happened here but the suggestion of @Corinna-Frank sounds perfect. We will fix this soon'ish (I am currently moving apartments, so I don't have a lot of time but maybe @gauchm can help out). Otherwise apply the fix that @Corinna-Frank suggests and you should be good to go.

**Comment by gauchm** [comment] 2023-01-27 19:15
Hi all,
I just had a look and you're absolutely right -- the issue is that the dataset is initialized before the scaler is loaded from the pretraining run. 
I created a fix that we'll merge as soon as @kratzert finds the time. It pretty much what @Corinna-Frank suggested (although the change in basedataset.py is not necessary, I think).

Thanks for reporting and helping to figure out the issue!

**Comment by everettsp** [comment] 2023-01-27 21:09
Thanks all! 
@Corinna-Frank's suggested change to `initialize_training` did the trick, and @gauchm is correct in that changes `basedataset.py` were not required.

**Comment by kratzert** [comment] 2023-01-30 13:47
Hi @everettsp,

thanks to @gauchm the fix should now be merged into the master branch of this repository. Would be great if you could verify that everything works for you.

**Closed by kratzert** 2023-01-30 13:47 UTC

**Comment by everettsp** [comment] 2023-01-30 19:45
Yep, everything's working now! Thanks @kratzert, and good luck with the new apartment.

**Comment by kratzert** [comment] 2023-01-30 20:19
Amazing. Thanks for reporting @everettsp and for already giving the hint what causes the problem, also thanks to @Corinna-Frank for her quick-fix and finally thanks @gauchm for submitting the fix.
